memory_limit = 4G
max_execution_time = 1800
upload_max_filesize = 64M
post_max_size = 64M
max_input_vars = 10000
date.timezone = Europe/Rome

opcache.enable = 1
opcache.memory_consumption = 512
opcache.max_accelerated_files = 60000
opcache.validate_timestamps = 1

realpath_cache_size = 10M
realpath_cache_ttl = 7200
